### ISSUE TITLE
Tikzdevice in R

### ISSUE THREAD

**Issue by josephsdavid** [xiaohanyu/awesome-tikz#4]
Hi I think there is an awesome resource to add to this, in R there is a library called tikzdevice, which allows for r graphical output, like ggplot2 wizardry, to be written into tikz code, for embedding in LaTeX documents etc. I have an example of using it in a Rnw document here: https://github.com/josephsdavid/MSDS/tree/master/MSDS6371/Homework/Week12 
and in a pure LaTeX document with R here https://github.com/josephsdavid/MSDS/tree/master/MSDS6371/Homework/Week8/Presentation !

**Comment by xiaohanyu** [comment]
Would you please propose a PR?

**Comment by josephsdavid** [comment]
Yes!

**Comment by josephsdavid** [comment]
Ok one question, relatively new to contributing, how do I create a pull request?

**Comment by xiaohanyu** [comment]
@josephsdavid https://help.github.com/articles/creating-a-pull-request/
