### ISSUE TITLE
TikZ has moved to GitHub

### ISSUE THREAD

**Issue by joulev** [xiaohanyu/awesome-tikz#5]
Ti*k*Z has moved from SourceForge to GitHub.

Now the official repository of Ti*k*Z - PGF is at https://github.com/pgf-tikz/pgf.

By the way, (just a little improvement) in README.md I think you should write Ti*k*Z (`Ti*k*Z`) instead of TikZ (`TikZ`). In the official "logo", the `k` is emphasized.

**Comment by xiaohanyu** [comment]
Fixed, fix the links, also I changed `TikZ` to `Ti*k*Z` in title and first paragraph.
